[[Tar]]
arch = "aarch64"
git-tree-sha1 = "80fac50858624879e97e382a84572ae019db9c4f"
os = "macos"

    [[Tar.download]]
    sha256 = "1d7a4e6631ee7ac4296f46d39a91a4b3fc3f9dfcdf9c22ffdbc5d213fddd47ef"
    url = "https://github.com/JuliaBinaryWrappers/Tar_jll.jl/releases/download/Tar-v1.34.0+0/Tar.v1.34.0.aarch64-apple-darwin.tar.gz"
[[Tar]]
arch = "aarch64"
git-tree-sha1 = "2c420f52f693dd247294244d363ebd539c10c0a3"
libc = "glibc"
os = "linux"

    [[Tar.download]]
    sha256 = "e6b1dd6bc8cd2adce14e9745d391d7d526f4212780553e4e9b4f54521c44bd63"
    url = "https://github.com/JuliaBinaryWrappers/Tar_jll.jl/releases/download/Tar-v1.34.0+0/Tar.v1.34.0.aarch64-linux-gnu.tar.gz"
[[Tar]]
arch = "aarch64"
git-tree-sha1 = "a1eb09190a1308cc3e1183d10617a0efa60e3175"
libc = "musl"
os = "linux"

    [[Tar.download]]
    sha256 = "0b9cf42d78b1ddfbf14baaeea0f90869d0166aef56412f8ae746355ecd68ad1c"
    url = "https://github.com/JuliaBinaryWrappers/Tar_jll.jl/releases/download/Tar-v1.34.0+0/Tar.v1.34.0.aarch64-linux-musl.tar.gz"
[[Tar]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e2c71372d21cd7d1fb0545c3aea5f19c45b7f750"
libc = "glibc"
os = "linux"

    [[Tar.download]]
    sha256 = "a383c67400adf39a640b83d8152cc01637f788619f36adce938ab2a840e61886"
    url = "https://github.com/JuliaBinaryWrappers/Tar_jll.jl/releases/download/Tar-v1.34.0+0/Tar.v1.34.0.armv6l-linux-gnueabihf.tar.gz"
[[Tar]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1696d936ff1b1c2baa538b40a7d4c0a842d05ae2"
libc = "musl"
os = "linux"

    [[Tar.download]]
    sha256 = "6ff658e29945d7620ff758f7afdd596b0523592bd17d38be404cfc0b73b9f3a9"
    url = "https://github.com/JuliaBinaryWrappers/Tar_jll.jl/releases/download/Tar-v1.34.0+0/Tar.v1.34.0.armv6l-linux-musleabihf.tar.gz"
[[Tar]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "afbcf9e8fe4ca2f3abf0ed826c9ba5eab0ae1869"
libc = "glibc"
os = "linux"

    [[Tar.download]]
    sha256 = "88404da0969a7453298d95b62c6cd3eccd22a5420ec6c9afcf5ca283564c3bb7"
    url = "https://github.com/JuliaBinaryWrappers/Tar_jll.jl/releases/download/Tar-v1.34.0+0/Tar.v1.34.0.armv7l-linux-gnueabihf.tar.gz"
[[Tar]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ff3ff9fc77134e0edc1b55547cb720860989725c"
libc = "musl"
os = "linux"

    [[Tar.download]]
    sha256 = "69c17adf3d3584ebce2bcf3f224fd2a6c67d3b7730bd5df89e3b13168c9eca05"
    url = "https://github.com/JuliaBinaryWrappers/Tar_jll.jl/releases/download/Tar-v1.34.0+0/Tar.v1.34.0.armv7l-linux-musleabihf.tar.gz"
[[Tar]]
arch = "i686"
git-tree-sha1 = "cdf73803888b1c1d2e91e1a07151cc0d0308c5c6"
libc = "glibc"
os = "linux"

    [[Tar.download]]
    sha256 = "026e84d10a07d62685dfa29d0f6b47f4b1cd4e0639b7ced188ea91053d0a4726"
    url = "https://github.com/JuliaBinaryWrappers/Tar_jll.jl/releases/download/Tar-v1.34.0+0/Tar.v1.34.0.i686-linux-gnu.tar.gz"
[[Tar]]
arch = "i686"
git-tree-sha1 = "627dcfd0673dfb5ea05446c3a770c46e99e2cca3"
libc = "musl"
os = "linux"

    [[Tar.download]]
    sha256 = "738ae6da41344bf8be970767e48a97ece195eff08cbdb117dc84cc5934d373de"
    url = "https://github.com/JuliaBinaryWrappers/Tar_jll.jl/releases/download/Tar-v1.34.0+0/Tar.v1.34.0.i686-linux-musl.tar.gz"
[[Tar]]
arch = "powerpc64le"
git-tree-sha1 = "44fc07ff530a0b19ba8bc103c9e3ef63917e0f0c"
libc = "glibc"
os = "linux"

    [[Tar.download]]
    sha256 = "5e66c7ab02d9d8e9be467ca8990dbe5eb23465df70778a378c7c3619681e5fb2"
    url = "https://github.com/JuliaBinaryWrappers/Tar_jll.jl/releases/download/Tar-v1.34.0+0/Tar.v1.34.0.powerpc64le-linux-gnu.tar.gz"
[[Tar]]
arch = "x86_64"
git-tree-sha1 = "953a9ff8b0f65d120059471d2795b548f194cc0c"
os = "macos"

    [[Tar.download]]
    sha256 = "30bd40a791197cb35377caacbb08c8002048a378261f1b4a09963025b50af226"
    url = "https://github.com/JuliaBinaryWrappers/Tar_jll.jl/releases/download/Tar-v1.34.0+0/Tar.v1.34.0.x86_64-apple-darwin.tar.gz"
[[Tar]]
arch = "x86_64"
git-tree-sha1 = "a5a1928599cad1e559e312d5c8345f5238aa9860"
libc = "glibc"
os = "linux"

    [[Tar.download]]
    sha256 = "35c4d61b8716829227d0c4305c018c53a69915ab9751401fd7864f4f88d36161"
    url = "https://github.com/JuliaBinaryWrappers/Tar_jll.jl/releases/download/Tar-v1.34.0+0/Tar.v1.34.0.x86_64-linux-gnu.tar.gz"
[[Tar]]
arch = "x86_64"
git-tree-sha1 = "2fd5c029da54ceb25a63abd46f5ee5c044c26ebd"
libc = "musl"
os = "linux"

    [[Tar.download]]
    sha256 = "d16283697be2348def34ddbd9d6fef1f12fe50f2d3b99868e1a8858d79bb94b5"
    url = "https://github.com/JuliaBinaryWrappers/Tar_jll.jl/releases/download/Tar-v1.34.0+0/Tar.v1.34.0.x86_64-linux-musl.tar.gz"
[[Tar]]
arch = "x86_64"
git-tree-sha1 = "2e9e10154122a6c24fd753c2f48718af52bf34ed"
os = "freebsd"

    [[Tar.download]]
    sha256 = "254e59255a9b79e9e1b296be54a4ff29f6e56a86d74d3b40442e1def657cb23c"
    url = "https://github.com/JuliaBinaryWrappers/Tar_jll.jl/releases/download/Tar-v1.34.0+0/Tar.v1.34.0.x86_64-unknown-freebsd.tar.gz"
