[[Tar]]
arch = "aarch64"
git-tree-sha1 = "e3ee64ab8a0ad3037e56d3bbe9cd63cd557660ae"
os = "macos"

    [[Tar.download]]
    sha256 = "d6641595c7e798ff2163b8d003b93017bb7a403bedd587a87cf91aca081f2831"
    url = "https://github.com/JuliaBinaryWrappers/Tar_jll.jl/releases/download/Tar-v1.34.0+1/Tar.v1.34.0.aarch64-apple-darwin.tar.gz"
[[Tar]]
arch = "aarch64"
git-tree-sha1 = "b50c7550c3f015386b7a753edefcbe83ba49d827"
libc = "glibc"
os = "linux"

    [[Tar.download]]
    sha256 = "84d75a076497cc049fc9cc5cd2f6c7d9780a2afcc1fe965854027f04564c8460"
    url = "https://github.com/JuliaBinaryWrappers/Tar_jll.jl/releases/download/Tar-v1.34.0+1/Tar.v1.34.0.aarch64-linux-gnu.tar.gz"
[[Tar]]
arch = "aarch64"
git-tree-sha1 = "5d1f22ec17e5ebd14d31380315fee1442e211398"
libc = "musl"
os = "linux"

    [[Tar.download]]
    sha256 = "693dbe8b92b5d112026e8db8417c3f9cb62ced3367a21d3ba6ba4eacaef37250"
    url = "https://github.com/JuliaBinaryWrappers/Tar_jll.jl/releases/download/Tar-v1.34.0+1/Tar.v1.34.0.aarch64-linux-musl.tar.gz"
[[Tar]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4fe950e14fade20e350b7d291bd3b5cb2eaedcbe"
libc = "glibc"
os = "linux"

    [[Tar.download]]
    sha256 = "e35e2dde82f09c367cdc9d8ac070d373409f386179617fb77fbc35de4909a4d5"
    url = "https://github.com/JuliaBinaryWrappers/Tar_jll.jl/releases/download/Tar-v1.34.0+1/Tar.v1.34.0.armv6l-linux-gnueabihf.tar.gz"
[[Tar]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "fb90c2534b87632004eaf2560a6f08615fe5df9d"
libc = "musl"
os = "linux"

    [[Tar.download]]
    sha256 = "d306e76dbf6c131cdc3ce109a1e7516668ed9497d0dc1e1280c10c7b7cd941a1"
    url = "https://github.com/JuliaBinaryWrappers/Tar_jll.jl/releases/download/Tar-v1.34.0+1/Tar.v1.34.0.armv6l-linux-musleabihf.tar.gz"
[[Tar]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2347cc9af2b09ea1990c9aee045d0a47ac532fc9"
libc = "glibc"
os = "linux"

    [[Tar.download]]
    sha256 = "862b57adeb10656cfe76f79fcb51308b44dc28fe08babf2fbd28d6da39e8baee"
    url = "https://github.com/JuliaBinaryWrappers/Tar_jll.jl/releases/download/Tar-v1.34.0+1/Tar.v1.34.0.armv7l-linux-gnueabihf.tar.gz"
[[Tar]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a44161940b29fa54c0f94ef1f5cd426d432e0749"
libc = "musl"
os = "linux"

    [[Tar.download]]
    sha256 = "8668fad99a9daf972e5981c5cca7546348f190266750d309e1383df6a0ef6988"
    url = "https://github.com/JuliaBinaryWrappers/Tar_jll.jl/releases/download/Tar-v1.34.0+1/Tar.v1.34.0.armv7l-linux-musleabihf.tar.gz"
[[Tar]]
arch = "i686"
git-tree-sha1 = "6e93bfc5182089afabc457c04b67db148dbef5bf"
libc = "glibc"
os = "linux"

    [[Tar.download]]
    sha256 = "b8fa85af0c2a9269bf4a585569d52cb7d173ff4ed4e6623b0b2d1eda063c9364"
    url = "https://github.com/JuliaBinaryWrappers/Tar_jll.jl/releases/download/Tar-v1.34.0+1/Tar.v1.34.0.i686-linux-gnu.tar.gz"
[[Tar]]
arch = "i686"
git-tree-sha1 = "7d289edcf8eeda95bc1a3b18751fd45cc7d62ab8"
libc = "musl"
os = "linux"

    [[Tar.download]]
    sha256 = "a4222874af65a6ec51f4cc721ca0df0595442cb6f217b9370c799ba106605ae1"
    url = "https://github.com/JuliaBinaryWrappers/Tar_jll.jl/releases/download/Tar-v1.34.0+1/Tar.v1.34.0.i686-linux-musl.tar.gz"
[[Tar]]
arch = "powerpc64le"
git-tree-sha1 = "540abbb509436d7fee11622ddcffc61e2f28d85b"
libc = "glibc"
os = "linux"

    [[Tar.download]]
    sha256 = "e26a62c37fda520ec3eae7da2be5bda0885bd6ba39a9223524b4de334d867ee2"
    url = "https://github.com/JuliaBinaryWrappers/Tar_jll.jl/releases/download/Tar-v1.34.0+1/Tar.v1.34.0.powerpc64le-linux-gnu.tar.gz"
[[Tar]]
arch = "x86_64"
git-tree-sha1 = "c9926a7483138b1997f8e033eeec51acb54cae5c"
os = "macos"

    [[Tar.download]]
    sha256 = "9e952962e10fdbeaacf80f0e6142a593c729bc741b7775c2803987a34c41d84c"
    url = "https://github.com/JuliaBinaryWrappers/Tar_jll.jl/releases/download/Tar-v1.34.0+1/Tar.v1.34.0.x86_64-apple-darwin.tar.gz"
[[Tar]]
arch = "x86_64"
git-tree-sha1 = "7db8f632fa90fd38bff4d2613e066b0750606f9e"
libc = "glibc"
os = "linux"

    [[Tar.download]]
    sha256 = "c6edf92c637fd6ec439de6549ef294797da77cff5e6e3582b7efc76bdd51061f"
    url = "https://github.com/JuliaBinaryWrappers/Tar_jll.jl/releases/download/Tar-v1.34.0+1/Tar.v1.34.0.x86_64-linux-gnu.tar.gz"
[[Tar]]
arch = "x86_64"
git-tree-sha1 = "fb2a85a6ba4fb0cedf9ce53e371fc276845e46cd"
libc = "musl"
os = "linux"

    [[Tar.download]]
    sha256 = "c612eddab8c3313503e203bae67e7a5fb88842a5c7371ad26ac045952a41eb24"
    url = "https://github.com/JuliaBinaryWrappers/Tar_jll.jl/releases/download/Tar-v1.34.0+1/Tar.v1.34.0.x86_64-linux-musl.tar.gz"
[[Tar]]
arch = "x86_64"
git-tree-sha1 = "c288b284bfabf0c2b1e06ba70aa6cc5c01448499"
os = "freebsd"

    [[Tar.download]]
    sha256 = "1c689a00dfd1a3c5cb1bfc7fa9b5879f88c64aaa983a4c76900d82fc7d457b36"
    url = "https://github.com/JuliaBinaryWrappers/Tar_jll.jl/releases/download/Tar-v1.34.0+1/Tar.v1.34.0.x86_64-unknown-freebsd.tar.gz"
