[[Tar]]
arch = "aarch64"
git-tree-sha1 = "b038a997d54bbc7b0c61eb1bc8b7f8c80a013015"
os = "macos"

    [[Tar.download]]
    sha256 = "1243fe3b96b5fde31eab90b5e74fc54c6756a152057ace199dfb73724da86508"
    url = "https://github.com/JuliaBinaryWrappers/Tar_jll.jl/releases/download/Tar-v1.35.0+0/Tar.v1.35.0.aarch64-apple-darwin.tar.gz"
[[Tar]]
arch = "aarch64"
git-tree-sha1 = "48098f4733626dc754e109fcc215fd59b7dcf873"
libc = "glibc"
os = "linux"

    [[Tar.download]]
    sha256 = "e35a24669311cb8b8503ac062d949025ae06b815fc995cfa5090ede9b29d0975"
    url = "https://github.com/JuliaBinaryWrappers/Tar_jll.jl/releases/download/Tar-v1.35.0+0/Tar.v1.35.0.aarch64-linux-gnu.tar.gz"
[[Tar]]
arch = "aarch64"
git-tree-sha1 = "84996aa074f550de8e7d13a618c27fc03270d140"
libc = "musl"
os = "linux"

    [[Tar.download]]
    sha256 = "7c3bc2c0b985300decb9ccabb4f8b475bf8c7a24d99509bd184e3b107436e90a"
    url = "https://github.com/JuliaBinaryWrappers/Tar_jll.jl/releases/download/Tar-v1.35.0+0/Tar.v1.35.0.aarch64-linux-musl.tar.gz"
[[Tar]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "99f69149f6f587ea8537be1afc3b2ccbcc53769f"
libc = "glibc"
os = "linux"

    [[Tar.download]]
    sha256 = "7e3a2f17426c965bc877b32dc9c14d65d4c98b2c062f74a24c5aa23de14ef665"
    url = "https://github.com/JuliaBinaryWrappers/Tar_jll.jl/releases/download/Tar-v1.35.0+0/Tar.v1.35.0.armv6l-linux-gnueabihf.tar.gz"
[[Tar]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7decb3c350c397cf418b4cb23c17f0cd000cc1dc"
libc = "musl"
os = "linux"

    [[Tar.download]]
    sha256 = "5849ad558e6c6cc49ba30481996086e51d320a71beb88777df2ae94816c37969"
    url = "https://github.com/JuliaBinaryWrappers/Tar_jll.jl/releases/download/Tar-v1.35.0+0/Tar.v1.35.0.armv6l-linux-musleabihf.tar.gz"
[[Tar]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b9008130a09a687df286f4155f26a5212e3e3ab4"
libc = "glibc"
os = "linux"

    [[Tar.download]]
    sha256 = "ae9ddd9e46b00faaa2053d3b084e43a1d8f7d4d45e9f761f19beaea8f9daf4ef"
    url = "https://github.com/JuliaBinaryWrappers/Tar_jll.jl/releases/download/Tar-v1.35.0+0/Tar.v1.35.0.armv7l-linux-gnueabihf.tar.gz"
[[Tar]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1e1c907ecb49172f78f173fc4a3fd66d18ce26be"
libc = "musl"
os = "linux"

    [[Tar.download]]
    sha256 = "31968bc05d3de3bb5637313d28ea9a385f590b5e2425eedd2393e043d3aef96f"
    url = "https://github.com/JuliaBinaryWrappers/Tar_jll.jl/releases/download/Tar-v1.35.0+0/Tar.v1.35.0.armv7l-linux-musleabihf.tar.gz"
[[Tar]]
arch = "i686"
git-tree-sha1 = "19939cee62fe0d04c7396669a7bf2f63361dca66"
libc = "glibc"
os = "linux"

    [[Tar.download]]
    sha256 = "88fa8abb6505f44945d02350fc153b61e0952249870fe1ade63ddda33942afc4"
    url = "https://github.com/JuliaBinaryWrappers/Tar_jll.jl/releases/download/Tar-v1.35.0+0/Tar.v1.35.0.i686-linux-gnu.tar.gz"
[[Tar]]
arch = "i686"
git-tree-sha1 = "de5a2b7957b5e3740e307428e72fcbe37c079575"
libc = "musl"
os = "linux"

    [[Tar.download]]
    sha256 = "39e67cf9456f8018096933dbe2c45b8ddc66adc000460f0affdf03ba022a8080"
    url = "https://github.com/JuliaBinaryWrappers/Tar_jll.jl/releases/download/Tar-v1.35.0+0/Tar.v1.35.0.i686-linux-musl.tar.gz"
[[Tar]]
arch = "powerpc64le"
git-tree-sha1 = "6600bd8a8bb62790f8b28c9aca08ae5e48fd79cc"
libc = "glibc"
os = "linux"

    [[Tar.download]]
    sha256 = "ab047df62b4313d0f94ee999385170cfb5a69fb20eef6c62d72ef33b99bc4c68"
    url = "https://github.com/JuliaBinaryWrappers/Tar_jll.jl/releases/download/Tar-v1.35.0+0/Tar.v1.35.0.powerpc64le-linux-gnu.tar.gz"
[[Tar]]
arch = "x86_64"
git-tree-sha1 = "9cfa202bca40350550dcceb7ac7f311cbe0de4b2"
os = "macos"

    [[Tar.download]]
    sha256 = "6429a5485b6914563e0bfbc3f820c08b3130e72fe27bca8b98a8c0bc586b61b6"
    url = "https://github.com/JuliaBinaryWrappers/Tar_jll.jl/releases/download/Tar-v1.35.0+0/Tar.v1.35.0.x86_64-apple-darwin.tar.gz"
[[Tar]]
arch = "x86_64"
git-tree-sha1 = "c1b8e405c143b54c372813d3e98b4489e808c122"
libc = "glibc"
os = "linux"

    [[Tar.download]]
    sha256 = "14ff8626e473ff0570384da559bf0468270303d1b1eaa9f27676b442e014a344"
    url = "https://github.com/JuliaBinaryWrappers/Tar_jll.jl/releases/download/Tar-v1.35.0+0/Tar.v1.35.0.x86_64-linux-gnu.tar.gz"
[[Tar]]
arch = "x86_64"
git-tree-sha1 = "548209f18ae4b19222d07b571d1c4868ea8e891a"
libc = "musl"
os = "linux"

    [[Tar.download]]
    sha256 = "9c3bd91ec4ddb0b21bc91d7b4ff35fd2aec547691bbb9f635c2161833311f9c7"
    url = "https://github.com/JuliaBinaryWrappers/Tar_jll.jl/releases/download/Tar-v1.35.0+0/Tar.v1.35.0.x86_64-linux-musl.tar.gz"
[[Tar]]
arch = "x86_64"
git-tree-sha1 = "9c2f56835472f2fe3f7e67019e13ed710f2fe3ff"
os = "freebsd"

    [[Tar.download]]
    sha256 = "07628f6de4c47f70fbc216a1923b61f9589f68a06756d060156012f59fae02c8"
    url = "https://github.com/JuliaBinaryWrappers/Tar_jll.jl/releases/download/Tar-v1.35.0+0/Tar.v1.35.0.x86_64-unknown-freebsd.tar.gz"
